//
//
//                                                                    Test.h
//

#ifndef TEST_H
#define TEST_H

#include <xlw/MyContainers.h>
#include <xlw/CellMatrix.h>
#include <xlw/DoubleOrNothing.h>
#include <xlw/ArgList.h>  
#include "volmodel.h"
#include "pricer.h"
#include "spotpricer.h"
#include "fxpricer.h"
#include "math_utils.h"
#include "timeseries.h"
#include "barriersmile.h"    
using namespace xlw;

//<xlw:libraryname=MyTestLibrary
MyArray CLFitDelta5VolParams(const double dtoday,
	const double dexp,
	const double fwd,
	const MyArray& strikeList,
	const MyArray& volList);

double CLSmileVolbyStrike(const double dtoday,
	const double dexp,
	const double fwd,
	const double atm,
	const double v90,
	const double v75,
	const double v25,
	const double v10,
	const double K,
	const std::string accrual);

double CLSmileVolbyDelta(const double dtoday,
	const double dexp,
	const double fwd,
	const double atm,
	const double v90,
	const double v75,
	const double v25,
	const double v10,
	const double delta,
	const std::string accrual);

double CLSmileEuroOptPricer(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double atm,
	const double v90,
	const double v75,
	const double v25,
	const double v10,
	const double doptexp,
	const double ir,
	const std::string otype,
	const std::string outflag,
	const double alpha,
	const double beta,
	const std::string accrual);

double CLEuroOptStrip(const double dtoday,
	const double dstart,
	const double dend,
	const double fwd,
	const double strike,
	const double atm,
	const double v90,
	const double v75,
	const double v25,
	const double v10,
	const double doptexp,
	const double ir,
	const std::string otype,
	const std::string outflag,
	const MyArray& hols,
	const double alpha,
	const double beta,
	const std::string accrual);

double CLSmileBinOptPricer(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double atm,
	const double v90,
	const double v75,
	const double v25,
	const double v10,
	const double doptexp,
	const double ir,
	const std::string otype,
	const std::string outflag,
	const double alpha,
	const double beta,
	const std::string accrual);

double CLDigitalStrip(const double dtoday,
	const double dstart,
	const double dend,
	const double fwd,
	const double strike,
	const double atm,
	const double v90,
	const double v75,
	const double v25,
	const double v10,
	const double doptexp,
	const double ir,
	const std::string otype,
	const std::string outflag,
	const MyArray& hols,
	const double alpha,
	const double beta,
	const std::string accrual);

double CLSprdOptPricer(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double atm,
	const double ir,
	const std::string otype,
	const std::string outflag,
	const std::string accrual);

double CLBlackImpliedVol(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double ir,
	const std::string otype,
	const double optPrice);

double CLBachelierImpliedVol(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double ir,
	const std::string otype,
	const double prem);

double CLBlackDelta(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double vol,
	const double ir,
	const std::string otype);

double CLBarrierFlatVolPricer(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double barrier,
	const std::string btype,
	const double atm,
	const double doptexp,
	const double ir,
	const std::string otype,
	const std::string mtype,
	const std::string outflag,
	const double alpha,
	const double beta,
	const std::string accrual);

double CLBarrierSmilePricer(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double barrier,
	const std::string btype,
	const double atm,
	const double v90,
	const double v75,
	const double v25,
	const double v10,
	const double doptexp,
	const double ir,
	const std::string otype,
	const std::string mtype,
	const std::string outflag,
	const double alpha,
	const double beta,
	const std::string accrual);

double CLBarrierStrip(const double dtoday,
	const double dstart,
	const double dend,
	const double fwd,
	const double strike,
	const double barrier,
	const std::string btype,
	const double atm,
	const double doptexp,
	const double ir,
	const std::string otype,
	const std::string mtype,
	const std::string outflag,
	const MyArray& hols,
	const double alpha,
	const double beta,
	const std::string accrual);

double CLBarrierSmileStrip(const double dtoday,
	const double dstart,
	const double dend,
	const double fwd,
	const double strike,
	const double barrier,
	const std::string btype,
	const double atm,
	const double v90,
	const double v75,
	const double v25,
	const double v10,
	const double doptexp,
	const double ir,
	const std::string otype,
	const std::string mtype,
	const std::string outflag,
	const MyArray& hols,
	const double alpha,
	const double beta,
	const std::string accrual);

double CLSpotBarrierPricer(const double dtoday,
	const double dexp,
	const double spot,
	const double strike,
	const double barrier,
	const std::string btype,
	const double atm,
	const double doptexp,
	const double ir,
	const double div,
	const std::string otype,
	const std::string mtype,
	const std::string outflag,
	const std::string accrual);

double CLSpotBarrierStrip(const double dtoday,
	const double dstart,
	const double dend,
	const double spot,
	const double strike,
	const double barrier,
	const std::string btype,
	const double atm,
	const double doptexp,
	const double ir,
	const double div,
	const std::string otype,
	const std::string mtype,
	const std::string outflag,
	const MyArray& hols,
	const std::string accrual);


double CLFXEuroOptPricer(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double atm,
	const double doptexp,
	const double ir,
	const std::string otype,
	MyArray& fxFwdTenors,
	MyArray& fxFwds,
	MyArray& fxVolTenors,
	MyArray& fxVols,
	const double corr,
	const std::string outflag,
	const double alpha,
	const double beta,
	const std::string accrual);

MyArray CLFXEuroOptRisks(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double atm,
	const double doptexp,
	const double ir,
	const std::string otype,
	MyArray& fxFwdTenors,
	MyArray& fxFwds,
	MyArray& fxVolTenors,
	MyArray& fxVols,
	const double corr,
	const std::string outflag,
	const double alpha,
	const double beta,
	const std::string accrual);

double CLFXEuroStripPricer(const double dtoday,
	const double dstart,
	const double dend,
	const double fwd,
	const double strike,
	const double atm,
	const double doptexp,
	const double ir,
	const std::string otype,
	MyArray& fxFwdTenors,
	MyArray& fxFwds,
	MyArray& fxVolTenors,
	MyArray& fxVols,
	const double corr,
	const std::string outflag,
	MyArray& hols,
	const double alpha,
	const double beta,
	const std::string accrual);

MyArray CLFXEuroStripRisks(const double dtoday,
	const double dstart,
	const double dend,
	const double fwd,
	const double strike,
	const double atm,
	const double doptexp,
	const double ir,
	const std::string otype,
	MyArray& fxFwdTenors,
	MyArray& fxFwds,
	MyArray& fxVolTenors,
	MyArray& fxVols,
	const double corr,
	const std::string outflag,
	MyArray& hols,
	const double alpha,
	const double beta,
	const std::string accrual);

double CLFXBinOptPricer(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double atm,
	const double doptexp,
	const double ir,
	const std::string otype,
	MyArray& fxFwdTenors,
	MyArray& fxFwds,
	MyArray& fxVolTenors,
	MyArray& fxVols,
	const double corr,
	const std::string outflag,
	const double alpha,
	const double beta,
	const std::string accrual);

MyArray CLFXBinOptRisks(const double dtoday,
	const double dexp,
	const double fwd,
	const double strike,
	const double atm,
	const double doptexp,
	const double ir,
	const std::string otype,
	MyArray& fxFwdTenors,
	MyArray& fxFwds,
	MyArray& fxVolTenors,
	MyArray& fxVols,
	const double corr,
	const std::string outflag,
	const double alpha,
	const double beta,
	const std::string accrual);

double CLFXBinStripPricer(const double dtoday,
	const double dstart,
	const double dend,
	const double fwd,
	const double strike,
	const double atm,
	const double doptexp,
	const double ir,
	const std::string otype,
	MyArray& fxFwdTenors,
	MyArray& fxFwds,
	MyArray& fxVolTenors,
	MyArray& fxVols,
	const double corr,
	const std::string outflag,
	MyArray& hols,
	const double alpha,
	const double beta,
	const std::string accrual);

MyArray CLFXBinStripRisks(const double dtoday,
	const double dstart,
	const double dend,
	const double fwd,
	const double strike,
	const double atm,
	const double doptexp,
	const double ir,
	const std::string otype,
	MyArray& fxFwdTenors,
	MyArray& fxFwds,
	MyArray& fxVolTenors,
	MyArray& fxVols,
	const double corr,
	const std::string outflag,
	MyArray& hols,
	const double alpha,
	const double beta,
	const std::string accrual);

#endif
