//// 
//// Autogenerated by xlw 
//// Do not edit this file, it will be overwritten 
//// by InterfaceGenerator 
////

#include "xlw/MyContainers.h"
#include <xlw/CellMatrix.h>
#include <stdexcept>
using namespace xlw;





MyArray  // too lazy to comment this function
mxlw_CLFitDelta5VolParams		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		MyArray strikeList, //too lazy to comment this one
		MyArray volList //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLSmileVolbyStrike		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double v90, //too lazy to comment this one
		double v75, //too lazy to comment this one
		double v25, //too lazy to comment this one
		double v10, //too lazy to comment this one
		double K //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLSmileVolbyDelta		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double v90, //too lazy to comment this one
		double v75, //too lazy to comment this one
		double v25, //too lazy to comment this one
		double v10, //too lazy to comment this one
		double delta //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLSmileEuroOptPricer		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double v90, //too lazy to comment this one
		double v75, //too lazy to comment this one
		double v25, //too lazy to comment this one
		double v10, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLEuroOptStripPricer		(
		double dtoday, //too lazy to comment this one
		double dstart, //too lazy to comment this one
		double dend, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double v90, //too lazy to comment this one
		double v75, //too lazy to comment this one
		double v25, //too lazy to comment this one
		double v10, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		MyArray hols, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLSmileBinOptPricer		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double v90, //too lazy to comment this one
		double v75, //too lazy to comment this one
		double v25, //too lazy to comment this one
		double v10, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLDigitalStripPricer		(
		double dtoday, //too lazy to comment this one
		double dstart, //too lazy to comment this one
		double dend, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double v90, //too lazy to comment this one
		double v75, //too lazy to comment this one
		double v25, //too lazy to comment this one
		double v10, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		MyArray hols, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLSprdOptPricer		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		std::string outflag //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLBlackImpliedVol		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		double optPrice //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLBachelierImpliedVol		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		double prem //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLBlackDelta		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double vol, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLBarrierOptFlatVolPricer		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double barrier, //too lazy to comment this one
		std::string btype, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		std::string mtype, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLBarrierOptSmilePricer		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double barrier, //too lazy to comment this one
		std::string btype, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double v90, //too lazy to comment this one
		double v75, //too lazy to comment this one
		double v25, //too lazy to comment this one
		double v10, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		std::string mtype, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLBarrierStripPricer		(
		double dtoday, //too lazy to comment this one
		double dstart, //too lazy to comment this one
		double dend, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double barrier, //too lazy to comment this one
		std::string btype, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		std::string mtype, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		MyArray hols, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
int  // too lazy to comment this function
mxlw_CLCalibHistBreakevenVol		(
		std::string hostname, //too lazy to comment this one
		std::string dbname, //too lazy to comment this one
		std::string tablename, //too lazy to comment this one
		int sprdnum, //too lazy to comment this one
		int expbackdays, //too lazy to comment this one
		int freq, //too lazy to comment this one
		MyArray contDates, //too lazy to comment this one
		std::string out_table //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLFXEuroOptPricer		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		MyArray fxFwdTenors, //too lazy to comment this one
		MyArray fxFwds, //too lazy to comment this one
		MyArray fxVolTenors, //too lazy to comment this one
		MyArray fxVols, //too lazy to comment this one
		double corr, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
MyArray  // too lazy to comment this function
mxlw_CLFXEuroOptRisks		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		MyArray fxFwdTenors, //too lazy to comment this one
		MyArray fxFwds, //too lazy to comment this one
		MyArray fxVolTenors, //too lazy to comment this one
		MyArray fxVols, //too lazy to comment this one
		double corr, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLFXEuroStripPricer		(
		double dtoday, //too lazy to comment this one
		double dstart, //too lazy to comment this one
		double dend, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		MyArray fxFwdTenors, //too lazy to comment this one
		MyArray fxFwds, //too lazy to comment this one
		MyArray fxVolTenors, //too lazy to comment this one
		MyArray fxVols, //too lazy to comment this one
		double corr, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		MyArray hols, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
MyArray  // too lazy to comment this function
mxlw_CLFXEuroStripRisks		(
		double dtoday, //too lazy to comment this one
		double dstart, //too lazy to comment this one
		double dend, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		MyArray fxFwdTenors, //too lazy to comment this one
		MyArray fxFwds, //too lazy to comment this one
		MyArray fxVolTenors, //too lazy to comment this one
		MyArray fxVols, //too lazy to comment this one
		double corr, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		MyArray hols, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLFXBinOptPricer		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		MyArray fxFwdTenors, //too lazy to comment this one
		MyArray fxFwds, //too lazy to comment this one
		MyArray fxVolTenors, //too lazy to comment this one
		MyArray fxVols, //too lazy to comment this one
		double corr, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
MyArray  // too lazy to comment this function
mxlw_CLFXBinOptRisks		(
		double dtoday, //too lazy to comment this one
		double dexp, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		MyArray fxFwdTenors, //too lazy to comment this one
		MyArray fxFwds, //too lazy to comment this one
		MyArray fxVolTenors, //too lazy to comment this one
		MyArray fxVols, //too lazy to comment this one
		double corr, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
double  // too lazy to comment this function
mxlw_CLFXBinStripPricer		(
		double dtoday, //too lazy to comment this one
		double dstart, //too lazy to comment this one
		double dend, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		MyArray fxFwdTenors, //too lazy to comment this one
		MyArray fxFwds, //too lazy to comment this one
		MyArray fxVolTenors, //too lazy to comment this one
		MyArray fxVols, //too lazy to comment this one
		double corr, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		MyArray hols, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
MyArray  // too lazy to comment this function
mxlw_CLFXBinStripRisks		(
		double dtoday, //too lazy to comment this one
		double dstart, //too lazy to comment this one
		double dend, //too lazy to comment this one
		double fwd, //too lazy to comment this one
		double strike, //too lazy to comment this one
		double atm, //too lazy to comment this one
		double doptexp, //too lazy to comment this one
		double ir, //too lazy to comment this one
		std::string otype, //too lazy to comment this one
		MyArray fxFwdTenors, //too lazy to comment this one
		MyArray fxFwds, //too lazy to comment this one
		MyArray fxVolTenors, //too lazy to comment this one
		MyArray fxVols, //too lazy to comment this one
		double corr, //too lazy to comment this one
		std::string outflag, //too lazy to comment this one
		MyArray hols, //too lazy to comment this one
		double alpha, //too lazy to comment this one
		double beta //too lazy to comment this one
 );
